coverage:
  status:
    project:
      default:
        target: 0.85
        threshold: 0.02
    patch:
      default:
        target: 0.80

comment:
  layout: "condensed, flags, files"
  behavior: default
