package web

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// tsTypes are the types the browser reads or sends, in the order they are
// written to web/src/api.gen.ts.
var tsTypes = []any{
	Issue{}, Comment{}, Snapshot{}, ProjectInfo{}, Health{}, Person{},
	ProjectEntry{}, ProjectList{}, OpenProjectRequest{}, QueryResult{},
	WriteRequest{}, WriteResult{}, Session{}, Event{},
}

var tsWriteOps = []WriteOp{OpStatus, OpClose, OpDelete, OpUpdate, OpCreate, OpComment, OpDefer}

const tsGenPath = "../../web/src/api.gen.ts"

// generateTypeScript renders the JSON contract as TypeScript. Only the kinds
// the contract uses are handled; anything else fails the test so a new field
// cannot slip through as "any".
func generateTypeScript() (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by go test ./pkg/web -run TestGeneratedTypesAreCurrent. DO NOT EDIT.\n")
	b.WriteString("// Source: pkg/web/types.go. Regenerate with `make web-types`.\n\n")

	ops := make([]string, len(tsWriteOps))
	for i, op := range tsWriteOps {
		ops[i] = fmt.Sprintf("%q", string(op))
	}
	fmt.Fprintf(&b, "export type WriteOp = %s;\n", strings.Join(ops, " | "))

	for _, v := range tsTypes {
		t := reflect.TypeOf(v)
		fmt.Fprintf(&b, "\nexport interface %s {\n", t.Name())
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			tag := f.Tag.Get("json")
			name, opts, _ := strings.Cut(tag, ",")
			if name == "" || name == "-" {
				return "", fmt.Errorf("%s.%s has no json name", t.Name(), f.Name)
			}
			ts, err := tsType(f.Type)
			if err != nil {
				return "", fmt.Errorf("%s.%s: %w", t.Name(), f.Name, err)
			}
			optional := ""
			if strings.Contains(opts, "omitempty") {
				optional = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", name, optional, ts)
		}
		b.WriteString("}\n")
	}
	return b.String(), nil
}

func tsType(t reflect.Type) (string, error) {
	if t == reflect.TypeOf(WriteOp("")) {
		return "WriteOp", nil
	}
	switch t.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int64, reflect.Uint64:
		return "number", nil
	case reflect.Slice:
		elem, err := tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "", fmt.Errorf("map key %s", t.Key())
		}
		elem, err := tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return "Record<string, " + elem + ">", nil
	case reflect.Struct:
		return t.Name(), nil
	}
	return "", fmt.Errorf("unsupported kind %s", t.Kind())
}

// TestGeneratedTypesAreCurrent keeps the browser's types in step with the
// Go contract. B9S_UPDATE_TS=1 rewrites the file instead of comparing.
func TestGeneratedTypesAreCurrent(t *testing.T) {
	want, err := generateTypeScript()
	if err != nil {
		t.Fatal(err)
	}
	if os.Getenv("B9S_UPDATE_TS") == "1" {
		if err := os.MkdirAll(filepath.Dir(tsGenPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(tsGenPath, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(tsGenPath)
	if err != nil {
		t.Fatalf("%v: run make web-types", err)
	}
	if string(got) != want {
		t.Fatal("web/src/api.gen.ts is out of date with pkg/web/types.go: run make web-types")
	}
}
