// Code generated by go test ./pkg/web -run TestGeneratedTypesAreCurrent. DO NOT EDIT.
// Source: pkg/web/types.go. Regenerate with `make web-types`.

export type WriteOp = "status" | "close" | "delete" | "update" | "create" | "comment" | "defer";

export interface Issue {
  id: string;
  title: string;
  description: string;
  design: string;
  acceptance: string;
  notes: string;
  status: string;
  priority: number;
  type: string;
  assignee: string;
  created_by: string;
  created_at: string;
  updated_at: string;
  closed_at: string;
  defer_until: string;
  labels: string[];
  parent: string;
  blocked_by: string[];
  related: string[];
  discovered_from: string[];
  comments: Comment[];
  comment_count: number;
  project: string;
  blocked: boolean;
  ready: boolean;
  closed_like: boolean;
}

export interface Comment {
  author: string;
  text: string;
  created_at: string;
}

export interface Snapshot {
  version: number;
  project: ProjectInfo;
  issues: Issue[];
  actor: string;
  people: Person[];
  health: Health;
}

export interface ProjectInfo {
  name: string;
  key: string;
  read_only: boolean;
  all: boolean;
}

export interface Health {
  ok: boolean;
  kind: string;
  source: string;
  watching: string;
  loaded_at: string;
  issues: number;
  fallback: string;
  error: string;
  bd_found: boolean;
}

export interface Person {
  name: string;
  kind: string;
  aliases: string[];
}

export interface ProjectEntry {
  slot: number;
  key: string;
  name: string;
  location: string;
  active: boolean;
  reach: string;
  open: number;
  in_progress: number;
  ready: number;
  blocked: number;
}

export interface ProjectList {
  projects: ProjectEntry[];
}

export interface OpenProjectRequest {
  key: string;
}

export interface QueryResult {
  version: number;
  ids: string[];
  error: string;
}

export interface WriteRequest {
  op: WriteOp;
  ids?: string[];
  status?: string;
  reason?: string;
  until?: string;
  text?: string;
  fields?: Record<string, string>;
  key?: string;
}

export interface WriteResult {
  ok: boolean;
  ids: string[];
  created: string;
  error: string;
  output: string;
  version: number;
}

export interface Session {
  csrf: string;
  query: string;
}

export interface Event {
  type: string;
  version: number;
}
